### ISSUE TITLE
Schedule by staff block

### ISSUE THREAD

**Issue by tianchengc** [tianchengc/exable-admin#10]
## 📝 Feature Description

Implement the calendar view of staff schedule, this is part of schedule page
Please use url /staff_schedule
<img width="833" alt="Screenshot 2024-11-30 at 5 29 43 PM" src="https://github.com/user-attachments/assets/d7553a28-4ae0-43bb-98df-7eb622d007a2">

---

## 🎨 Design URL

https://js.design/v?i=gNMMz4&p=zCNLbPnMlU&f=0:840

---

## ⏱️ Time Estimate

- **Estimated Hours:** 16 hours  

---

## 💡 Hints / Additional Notes

- **Hint 1:**  Create schedule page first and set up router
- **Hint 2:**  Create calendar component inside schedule page
- **Hint 3:**  

---

## 📄 Acceptance Criteria

- [ ] Implement interface according to design
- [ ] Connect interface with api
- [ ] Pass manual test  

---

**Comment by zdyyyy** [comment]
https://github.com/tianchengc/exable-admin/pull/58 I pulled a request
