### ISSUE TITLE
Dashboard - Overview Block

### ISSUE THREAD

**Issue by tianchengc** [tianchengc/exable-admin#13]
## 📝 Feature Description

Implement overview block in landing dashboard. 
Use static numbers for the interface.
Leave class and cycle dropdown list empty.
Connect api is tracked https://github.com/tianchengc/exable-admin/issues/25
<img width="704" alt="Screenshot 2024-11-28 at 12 25 57 AM" src="https://github.com/user-attachments/assets/e86607ec-8893-4501-b4ec-9c3bdf453564">

---

## 🎨 Design URL

[Design URL](https://js.design/v?i=gNMMz4&p=zCNLbPnMlU&f=0:354)

---

## ⏱️ Time Estimate

- **Estimated Hours:** 8 hours  

---

## 📄 Acceptance Criteria

- [ ] Implement interface according to design
- [ ] NOT Required: Connect interface with api
- [ ] Pass manual test  

---

**Comment by tianchengc** [comment]
@AKalyanPavan please pull latest main branch into your dev branch and reinstall dependancies, there was a major change pushed to main branch

**Comment by tianchengc** [comment]
@ericmaic @uiynyny could you provide the api detail for these numbers?

**Comment by AKalyanPavan** [comment]
@tianchengc, Sure, I'll check that.

**Comment by tianchengc** [comment]
Hi @AKalyanPavan are you still on this? Do you need any help?
