### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by tianchengc** [tianchengc/exable-admin#15]
## 📝 Feature Description
Registration page including registration form.
Registration form can be reused in [account page](https://js.design/v?i=gNMMz4&p=zCNLbPnMlU&f=0:1472&mode=programmer), recommend to make registration form a separated component.
Page url should be /register

---

## 🎨 Design URL

[Design URL](https://js.design/v?i=gNMMz4&p=zCNLbPnMlU&f=0:1978)

---

## ⏱️ Time Estimate

- **Estimated Hours:**16 hours  

---

## 💡 Hints / Additional Notes

- **Hint 1:**  Image file is at src/assets/login_image.svg
- **Hint 2:**  Province dropdown options are static list of Canadian provinces, like Ontario, Quebec etc. this can be hardcoded.
- **Hint 3:**  Role in organization dropdown needs to be confirmed, tracked here https://github.com/tianchengc/exable-admin/issues/24

---

## 📄 Acceptance Criteria

- [ ] Implement interface according to design
- [ ] Connect interface with api
- [ ] Pass manual test  

---

**Comment by aaronamoso** [comment]
Hello, I cannot seem to npm start the program. I tried to download node_modules but is still giving me error.

Error: Cannot find module 'C:\Projects\exable-admin\node_modules\react-scripts\bin\react-scripts.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by tianchengc** [comment]
@aaronamoso please pull latest main branch into your dev branch and reinstall dependancies, there was a major change pushed to main branch

**Comment by tianchengc** [comment]
@aaronamoso are you still on this? Could share your progress if possible, thanks

**Comment by aaronamoso** [comment]
Yes, still working on it! Sorry for the delay! I got the dependencies sorted the second you updated me! So I can easily transfer my current work to the main repo

**Comment by tianchengc** [comment]
> Yes, still working on it! Sorry for the delay! I got the dependencies sorted the second you updated me! So I can easily transfer my current work to the main repo

Awesome, thank you man!

**Comment by aaronamoso** [comment]
Did you also want me to create input validation? Or leave that for the backend

**Comment by aaronamoso** [comment]
![Screenshot 2024-12-04 012919](https://github.com/user-attachments/assets/6e9ee525-c76a-4b4c-8285-4bdf195bf8f2)
Current of what I have, I have never worked with TS before and the whole time I did it in jsx. But I did type it in typescript and commit! Also, there were some issues with me routing it to /register. I created my part on the page > register > {reg files..}. Let me know what you think!

**Comment by tianchengc** [comment]
> ![Screenshot 2024-12-04 012919](https://private-user-images.githubusercontent.com/104960696/392289840-6e9ee525-c76a-4b4c-8285-4bdf195bf8f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MzA0MDMsIm5iZiI6MTczMzQzMDEwMywicGF0aCI6Ii8xMDQ5NjA2OTYvMzkyMjg5ODQwLTZlOWVlNTI1LWM3NmEtNGI0Yy04Mjg1LTRiZGYxOTViZjhmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQyMDIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTdhYzk0MDU3YjFlNzRhMDRkNDJkODNhNWJjZWZhZTQ1YWYzNWE5ZDU2NTlhZTIwNjBhNWI4MjgxODZlMTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AOIkEo6phgoiY5ceFEx4qA7eAa1N-I0REMU9KPZfaho) Current of what I have, I have never worked with TS before and the whole time I did it in jsx. But I did type it in typescript and commit! Also, there were some issues with me routing it to /register. I created my part on the page > register > {reg files..}. Let me know what you think!

@aaronamoso nice job! Typescript can be useful to make the code clean and avoid surprising errors, you can take this project to practice it.

Could you fix the styling and create a pull request for this?
