### ISSUE TITLE
Schedule Page

### ISSUE THREAD

**Issue by tianchengc** [tianchengc/exable-admin#22]
## 📝 Feature Description

Implement schedule page, the url of this page should be /schedule
The buttons should link to /staff_schedule and /class_schedule
<img width="1122" alt="Screenshot 2024-11-27 at 10 50 15 AM" src="https://github.com/user-attachments/assets/76128527-8cdc-46ed-84ad-86d64a96aea5">

---

## 🎨 Design URL

[Design URL](https://js.design/v?i=gNMMz4&p=zCNLbPnMlU&f=73:323&mode=programmer)

---

## ⏱️ Time Estimate

- **Estimated Hours:** 6 hours  

---

## 💡 Hints / Additional Notes

- **Hint 1:**  The image is at src/assets/schedule_image.svg

---

## 📄 Acceptance Criteria

- [ ] Implement interface according to design
- [ ] Pass manual test  

---

**Comment by NewFish007** [comment]
Hi. May I join you in this task? email: zero0lancelot@gmail.com

**Comment by tianchengc** [comment]
@zdyyyy @NewFish007 please pull latest main branch into your dev branch and reinstall dependancies, there was a major change pushed to main branch

**Comment by zdyyyy** [comment]
> @zdyyyy @NewFish007 please pull latest main branch into your dev branch and reinstall dependancies, there was a major change pushed to main branch

OK, sure

**Comment by NewFish007** [comment]
@zdyyyy Feel free to contact me at any time and we can have a meeting to discuss the task

**Comment by zdyyyy** [comment]
Cool, maybe tonight or tomorrow?

**Comment by zdyyyy** [comment]
> @zdyyyy Feel free to contact me at any time and we can have a meeting to discuss the task

Cool, maybe tonight or tomorrow?

**Comment by NewFish007** [comment]
Sure

**Comment by NewFish007** [comment]
Sure, no problem. What's your name on Gather?

**Comment by zdyyyy** [comment]
I haven't registered yet lol. I will show you later.

**Comment by zdyyyy** [comment]
> Sure, no problem. What's your name on Gather?

I haven't registered yet lol. I will show you later.

**Comment by zdyyyy** [comment]
> Sure, no problem. What's your name on Gather?

My name in Gather is Ronald Yin.

**Comment by NewFish007** [comment]
> > Sure, no problem. What's your name on Gather?
> 
> My name in Gather is Ronald Yin.

My name is Lance

**Comment by zdyyyy** [comment]
> > > Sure, no problem. What's your name on Gather?
> > 
> > 
> > My name in Gather is Ronald Yin.
> 
> My name is Lance

OK, see you then.

**Comment by tianchengc** [comment]
You guys are amazing! Don't forget to connect on Linkedin!

**Comment by zdyyyy** [comment]
I have modified Lance' sidebar including the background, button, active and hover color. Thanks to his work.
Here is the link: https://github.com/tianchengc/exable-admin/pull/42

**Comment by NewFish007** [comment]
> I have modified Lance' sidebar including the background, button, active and hover color. Thanks to his work. Here is the link: #42

@zdyyyy Nice work! I can't get through to Gather to leave you a message. It would be nice to know your LinkedIn.
