### ISSUE TITLE
Side Navigation

### ISSUE THREAD

**Issue by tianchengc** [tianchengc/exable-admin#27]
## 📝 Feature Description

Implement side navigation bar with buttons and profile image. Side nav is fixed to the right of the interface.

Buttons are link to following page urls
/schedule
/participants
/resources
/reports
/library

![Screenshot 2024-11-28 at 11 52 59 AM](https://github.com/user-attachments/assets/c1d3ee0d-c2b0-4e11-973f-d463cb258fd0)

---

## 🎨 Design URL

https://js.design/v?i=gNMMz4&p=zCNLbPnMlU&f=0:354&mode=programmer

---

## ⏱️ Time Estimate

- **Estimated Hours:** 4 hours   

---

## 📄 Acceptance Criteria

- [ ] Implement interface according to design
- [ ] Connect interface with api
- [ ] Pass manual test  

---

**Comment by tianchengc** [comment]
@zdyyyy please pull latest main branch into your dev branch and reinstall dependancies, there was a major change pushed to main branch, there might be merge conflict, if you have question with them, please send to discord channel

**Comment by zdyyyy** [comment]
> @zdyyyy please pull latest main branch into your dev branch and reinstall dependancies, there was a major change pushed to main branch, there might be merge conflict, if you have question with them, please send to discord channel

OK, got it.
