### ISSUE TITLE
Error installing node modules

### ISSUE THREAD

**Issue by swapnils118** [tianchengc/exable-admin#31]
Weird version type errors while installing node modules once we take clone from main branch.
<img width="1440" alt="Screenshot 2024-11-29 at 12 53 22 AM" src="https://github.com/user-attachments/assets/2db5a2a9-0f9f-4e4e-b1f6-3a91dc93430e">

**Comment by dgtlmonk** [comment]
I believe this is caused by `node-sass`.

<img width="310" alt="image" src="https://github.com/user-attachments/assets/3be094b4-169f-40a9-9cc6-960271470c1e">

I've encountered this a while ago, tried to fix but no success (unless I remove `node-sass` from dependencies - but ran into other issues. 

I've [issued](https://github.com/tianchengc/exable-admin/issues/30) a similar concern, I believe @tianchengc  is working on this.

**Comment by swapnils118** [comment]
Thanks for your response @dgtlmonk  and yes we both are working towards fixing this.
Can you tell me from your experience on how did you make the code work then in order to start developing/contributing further?
Your any response is much appreciated.
Thanks

**Comment by dgtlmonk** [comment]
@swapnils118 I am still stuck in not being able to run this codebase. 

@tianchengc, when you are free; could you clone this repo and try to run yourself if you don't get this same issue when installing fresh dependencies?

**Comment by swapnils118** [comment]
If we either remove node-sass or run npm install --peer-legacy-peer-deps, we are getting errors as:
<img width="1440" alt="Error1" src="https://github.com/user-attachments/assets/15691f2d-f1b0-43e4-ac97-0857ed2f5e4d">

**Comment by dgtlmonk** [comment]
Yeah, looks like this "glitch" is cross-dependency issues. I suggest, we start from scratch while there's not much code in here. 

I also suggest, we add the dependencies as needed - i noticed we have too many dependencies that are unnecessary upfront. 

I can help set a fresh repo if needed.

**Comment by swapnils118** [comment]
Yes I also support this side. But still I will dig deep into these issues and try to find the catch.

**Comment by tianchengc** [comment]
@swapnils118 could you validate again with latest main branch, @dgtlmonk has fixed it

**Comment by swapnils118** [comment]
@tianchengc  Yes I am back to work. Let me have a look.

**Comment by swapnils118** [comment]
@Take care The problem is solved. 
A big thanks to @dgtlmonk

**Comment by tianchengc** [comment]
Thanks for confirming!
