### ISSUE TITLE
Error Installing node-modules due to deprecated packages

### ISSUE THREAD

**Issue by Mikey1233** [tianchengc/exable-admin#32]
## 📝 Feature Description
warning " > react-google-login@5.2.2" has incorrect peer dependency "react@^16 || ^17".
warning " > react-google-login@5.2.2" has incorrect peer dependency "react-dom@^16 || ^17".
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".

## 🎨 Design URL

[Design URL](<insert-design-url-here>)

---

## 📋 Feature Details

---

## ⏱️ Time Estimate

- **Estimated Hours:** XX hours  

---

## 🌐 Related URLs

- [Relevant Documentation](<insert-documentation-url-here>)  
- [Related Issue/PR](<insert-related-url-here>)  

---

## 💡 Hints / Additional Notes

- **Hint 1:**  
- **Hint 2:**  
- **Hint 3:**  

---

## 📄 Acceptance Criteria

- [ ] Implement interface according to design
- [ ] Connect interface with api
- [ ] Pass manual test  

---

**Comment by tianchengc** [comment]
Hi @Mikey1233 could you validate if it works for you with latest main branch
