### ISSUE TITLE
400 error google Oauth

### ISSUE THREAD

**Issue by YeomChaeeun** [tianchengc/exable-admin#34]
## 📝 Feature Description

After resolving several npm install issues, I tried running the project. but I am being redirected to /login and the Google login page appears. However, It's 400 error.

Do I need to manually generate an OAuth localhost key to implement this, or is there a different approach?
 For example, could you add my Google email instead?

Additionally, in the package.json file, the "proxy" was set to "http://localhost:8080/". Is there any way to get a different accessible server address for the API?

Thanks in advance for your help!

![unnamed](https://github.com/user-attachments/assets/3e898636-b9e9-42b9-8f18-b3f2583924aa)

---

## 🎨 Design URL

[Design URL](<insert-design-url-here>)

---

## 📋 Feature Details

---

## ⏱️ Time Estimate

- **Estimated Hours:** XX hours  

---

## 🌐 Related URLs

- [Relevant Documentation](<insert-documentation-url-here>)  
- [Related Issue/PR](<insert-related-url-here>)  

---

## 💡 Hints / Additional Notes

---

## 📄 Acceptance Criteria

---

**Comment by alicelee1231** [comment]
I also tried login, but I occured same problem. so I deleted the Oauth thing for accessing the page, but it also didn't work...
@tianchengc

**Comment by tianchengc** [comment]
@alicelee1231 @YeomChaeeun could you try again with latest main branch, @dgtlmonk updated it with google auth removed

**Comment by alicelee1231** [comment]
@tianchengc  thanks! it is working!!

**Comment by YeomChaeeun** [comment]
@tianchengc thank you! it's working now!

**Comment by tianchengc** [comment]
Thank you for confirming!
