### ISSUE TITLE
Schedule of all classes block

### ISSUE THREAD

**Issue by tianchengc** [tianchengc/exable-admin#9]
## 📝 Feature Description

Implement class schedule component inside /class_schedule
<img width="725" alt="Screenshot 2024-11-30 at 5 35 09 PM" src="https://github.com/user-attachments/assets/1cd59b4b-037d-4444-8be0-d13f6cd0c6ea">

---

## 🎨 Design URL

https://js.design/v?i=gNMMz4&p=zCNLbPnMlU&f=77:8

---

## ⏱️ Time Estimate

- **Estimated Hours:** 16 hours  

---

## 📄 Acceptance Criteria

- [ ] Implement interface according to design
- [x] Connect interface with api
- [ ] Pass manual test  

---

**Comment by NewFish007** [comment]
I'm trying to accomplish this. But I don't know how to assign it to myself
